#Formatting Guidelines

*Author: Martin Lysy, Trang Bui*

*Last Updated: Nov 09, 2020*

$$~$$

## General

- Let's agree to use regular font for programming languages (e.g., R, Python, C++) and bold font for packages and libraries (e.g., **TMB**, **rstan**, **NumPy**, **Tensorflow**).

- Please see Appendix [B.2.3][Citations] for how to handle citations.

- To refer to figures/tables/sections, the standard academic style is e.g., "Figure 2", "Section 2.5", etc.  In other words, capital letter, no bold/italics, and hyperlink for the number.  See relevant **bookdown** [chapter](https://bookdown.org/yihui/bookdown/figures.html) for how to do this!

- Paragraph breaks are simply indicated by one ore more empty lines.  No need for `\newline` or anything else.  This applies to elements other than text such as figures, math blocks etc.  If the figure/math block/etc is part of the paragraph, don't leave blank spaces before or after^[An exception to this is possibly within an indented region.  There you may need to leave a blank space before/after math block...I'm not 100% sure...].

- Please use Capital Case for all section headings, for example, Plan the Study.

- Our concensus for writing in a list are mentioned below. For details, visit [here](https://getitwriteonline.com/articles/vertical-lists/).
 
    - If the items in the list are complete sentences, begin the first word in each item with a capital-case letter and end the item with period.
    - If the items are single words and phrases, begin the first word in each item with a lower-case letter and end with a colon. Use "and" (or "or", depending on the context of the list) after the next-to-last item, and use a period after the last item in the list.
    - If the items are phrases or clauses with punctuations in them, put a semicolon at the end of each item. Put "and" (or "or") after the next-to-last item in the list and period for the last item. The items are not capitalized. 

## Math

- Always use bold font like $\XX$^[LaTeX purists might prefer to use `\mathbf{}` for roman letters instead of `\boldsymbol{}` as I have defined via the `\bm{}` macro in `preamble.html`.  Observe the difference: $\mathbf{x}$ vs $\boldsymbol{x}$ and $\mathbf{X}$ vs $\boldsymbol{X}$.  For pure LaTeX, the `\bm{}` command in the [**bm**](https://ctan.org/pkg/bm?lang=en) package automagically picks the right one for you.  Eventually I'll figure out how to use this package for the e-book, in which case if you consistently use `\bm{}` for bold there will be very little for me to change!] or $\aal$ for anything that isn't a scalar.  In particular, please use `\bm{}` command in math mode to make things bold, and note that bold letters and symbols have standard macros as explained in `index.Rmd`.  Please use them!

- If applicable distinguish between vectors and matrices (or collections of vectors) with lower and upper case, like $\yy$ and $\YY$ or $\tth$ and $\TTh$.  

- Equations are part of sentences, so use punctuation in them, e.g., for observations $\XX = (\rv X N)$ such that

$$
	\begin{aligned} 
	X_i \mid \mu_i & \ind \N(\mu_i, \sigma_i^2) \\
	\mu_i & \iid \N(0, \tau^2).
	\end{aligned}
	(\#eq:mathex)
$$

### Commonly-Used Math and Stats Expressions

- Sequences of random variables: $X_1, \ldots, X_N$.  In fact since these are so common, I've created a macro for it: $\rv Y 5$ and $\rv [m,0] Z {m,N_m}$.

- For multi-line equations with alignment, use `aligned` environment as in \@ref(eq:mathex).

- The "d" in integrals:
    $$
    \ud X_t = \mu(X_t) \ud t + \ud B_t \qquad \iff \qquad X_t = \mu t + \int_0^t \mu(X_t) \ud t + B_t.
    $$

- Conditioning: $p(y \mid x)$

- Independence: $Y \amalg X$

- Probability: $\Pr(Y \le y)$

- Derivatives and partials: These are quite time-consumming to typeset so I've created some macros for them:
    $$
	\der{x} f(x), \qquad \fdel[3]{x} {g(x, y)}, \qquad \hess{\tth}\ell(\tth \mid \XX).
	$$
	The last of these is used for Hessian matrices.

- Independent/IID/Normal: Please see \@ref(eq:mathex).

- Variance/Covariance/Correlation: $\var(X), \cov(X), \cor(X)$.