# (APPENDIX) Appendix {-} 

# General Guidelines

*Author: Martin Lysy*

*Last Updated: Nov 17, 2020*

--- 

## Resources

- **R Markdown:** The  [**bookdown** e-book](https://bookdown.org/yihui/bookdown/) the [Definitive R Markdown Guide](https://bookdown.org/yihui/rmarkdown/) and the [R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/).

- **LaTeX:** <a name="genguide-res:latex"> [Basic](https://en.wikibooks.org/wiki/LaTeX/Mathematics) and [advanced](https://en.wikibooks.org/wiki/LaTeX/Advanced_Mathematics) math formatting guides.

- **Collaborations:** The [Pro Git book](https://git-scm.com/book/en/v2), and a quick tutorial [here][Git and GitHub: A Quick Tutorial].

## Bookdown

[**bookdown**](https://bookdown.org/yihui/bookdown/) is an R package which allows us to integrate scientific writing (including math, figures, etc.) with executable programming blocks.  While **bookdown** is interfaced through R, very little R knowledge is required to operate it.  The scientific writing is done in Markdown and LaTeX, whereas the programming blocks can be written in R, Python, Julia, C++, etc.

### Rendering the Book

For this you will need to install the packages that are required in each of the module. Once you have the packages installed, quit + restart R for safe measure.  Then, from within the project folder, run

```{r app-gen-render, eval = FALSE}
bookdown::render_book()
```

To make sure everything is working as expected, you may wish to delete the `_book` and `_bookdown_files` folders before rendering.  These don't get cleaned up between runs, so there might be very old files hanging around in there if you don't periodically perform a manual cleanup.

## Content

In building content for the modules,

- Keep in mind that our target readers are those who have light background in statistics. Try explaining the concepts in an easy and intuitive way. Also, focus on the practicality of the module, i.e., how the readers are going to use the knowledge or code presented in the module in their research. Having one or two running examples would greatly helps the readers understand the modules more effectively. 

- Set up the code in a clear and well-organized manner, use lots of code comments, informative variable names, and consistent naming conventions, etc. 

In terms of formatting the content with R Markdown, please refer to the [Formatting Guidelines](#appformattingguidelines).

