---
title: "Topics in Statistical Consulting"
author: |
  | **Statistical Consulting and Collaborative Research Unit**
  | **University of Waterloo**
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
biblio-style: apalike
link-citations: true
bibliography: ["references.bib"]
output: 
  bookdown::gitbook:
    fig_caption: yes
    includes:
      in_header: preamble.html
---

# Project Description

In this assignment you are asked to develop the slides and code examples from a module of your choice into a proper set of notes^[You may also contribute your own module relating to Bayesian computing.  Please contact me if you wish to do this.].  Students may elect to have their notes become part of an e-book on Bayesian computing which I will publicly host online. All students collaborating on the e-book will be listed as co-authors.

## Objectives

- Gain a confident understanding of a topic in Bayesian computing, and clearly communicate it to an audience having an undergraduate background in statistics.

- Develop a good workflow within a complex programming environment integrating Markdown, LaTeX, statistical software, and Git.

<!-- - Use a production-grade software tool or program for the purpose of Bayesian computing. -->

## Resources

- **R Markdown:** The  [**bookdown** e-book](https://bookdown.org/yihui/bookdown/) the [Definitive R Markdown Guide](https://bookdown.org/yihui/rmarkdown/) and the [R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/).

- **LaTeX:** <a name="res:latex"></a> [Basic](https://en.wikibooks.org/wiki/LaTeX/Mathematics) and [advanced](https://en.wikibooks.org/wiki/LaTeX/Advanced_Mathematics) math formatting guides.

- **Content:** The LaTeX code to generate a much-updated version of the course's [slides](slides/README.md) and [example code](code/README.md).

- **Git:** The [Pro Git book](https://git-scm.com/book/en/v2), and a quick tutorial here.

- **Collaboration:**  Since most of you are working on modules in teams and meetings need to be done remotely, please check on LEARN under "Content/Resources" for a document describing how you can set up online group meetings using UW Webex.

## Format

Your notes must be produced with [**bookdown**](https://bookdown.org/yihui/bookdown/), an R package which allows you to integrate scientific writing (including math, figures, etc.) with executable programming blocks.  While **bookdown** is interfaced through R, very little R knowledge is required to operate it.  The scientific writing is done in Markdown and LaTeX, whereas the programming blocks can be written in R, Python, Julia, C++, etc.

<!-- The content of each module can roughly be divided into three components: -->

<!-- 1.  Text explaining the concepts, models, etc. -->

<!-- 2.  Short snippets of code which contribute to understanding the text (e.g., loading and displaying parts of datasets, simple calculations), or which can be used to create figures and tables. -->

<!-- 3.  Larger sections of code consisting of interdependent functions, data processing, complex plotting functions, etc.  Some of this code can be displayed within the text, but by and large it should be written in -->

Each module should consist of:

- One `Rmd` file containing the Markdown/LaTeX text, and short snippets of code which contribute to understanding the text (e.g., loading and displaying parts of datasets, simple calculations), or which can be used to create figures and tables.

- Any number of external `.R`, `.py`, `.jl`, `.cpp`, etc. files for anything more complicated, e.g., interdependent and longer functions, data preprocessing files, etc.  I strongly recommend that you do not put too much code into `Rmd` files directly as it makes it much more difficult to organize, debug, and maintain.

- Do provide links to relevant resources: papers, blogposts, etc. which helped you understand things better, and also any *high quality/performance* software to use or explore.  I've tried to provide such resources in my notes; please do update if links are broken, libraries have been superceeded, etc.

Students may work alone or in groups.  All submissions must be done via GitHub (see details [below](#git)).

<!-- the software.  I strongly recommend that you never try to write in multiple programming languages at once (e.g., R + Markdown). -->

<!-- A skeleton for the full set of notes (including all modules) is to be downloaded from GitHub.  Each module should consist of an `Rmd` file containing the Markdown/LaTeX text, and external `.R`, `.py`, `.jl`, `.cpp`, etc. files for the software.  I strongly recommend that you never try to write in multiple programming languages at once (e.g., R + Markdown). -->

### Style

Don't worry about formatting details regarding the appearance of the e-book as these will be set later at the global level.  Instead, please focus on:

i.  Creating a clear organization of topics within your module using section/subsection/subsubsection headers

ii.  Setting up the code for examples in a clear and well-organized manner, i.e., what to include directly in the `.Rmd` file and what goes into external scripts, lots of code comments, informative variable names and consistent naming conventions, etc.

### Typesetting Math

Please do take a look at the [LaTeX guides](#res:latex) above, as it is easy to do this right and very annoying to redo if you do it wrong.

One extremely useful LaTeX feature is the ability to define macros for commonly used commands.  I strongly encourage you to use macros whenever possible.  Not only does this save a considerable amount of typing, but also often an enormous amount of search-replacing.  For example, suppose I have a canonical transformation function which I'll be using throughout the document, but I'm not quite sure how to typeset it yet.  So I define the LaTeX macro `\ctran` and use it.  If later I want to redefine how `\ctran` is typeset that's an extremely easy fix.

Another useful LaTeX trick is to use simple patterns to define macros for common things.  For example, I always define bold letter names (which you should use for anything that isn't a scalar) as `\xx` `\YY`, etc., and bold symbol names as `\aal` for $\boldsymbol{\alpha}$, `\TTh` for $\boldsymbol{\Theta}$, etc. 

As a rule-of-thumb, **avoid** defining one-letter macros.  The worst LaTeX mistake I've ever made is to define $\beta$ as`\b` in everything LaTeX document I wrote before 2015.  Now suppose I want to replace $\beta$ by $\gamma$ as a symbol for the quantity of interest.  Then either I have an extremely confusing macro `\newcommand{\b}{\gamma}`, or the most annoying search-replace ever (`\begin{xyz}` anyone?).  Sometimes I do use one letter capital macros, e.g., `\newcommand{\N}{\mathcal{N}}` for the normal distribution, but these are much easier to search-replace.

For this project, LaTeX is rendered to HTML via [Mathjax](https://www.mathjax.org/), and thus the macros must be defined a bit differently than in regular LaTeX.  All LaTeX macros must be defined in [`preamble.html`](preamble.html).

### Citations

For external websites it's sufficient to provide a link as I've done in this document.  For journal articles, textbooks, conference proceedings etc. it's good practice to provide the complete citation information (in addition to a link to the resource if it can be obtained legally for free).  For such references please use [BibTeX](https://en.wikibooks.org/wiki/LaTeX/Bibliography_Management) with a module specific bibliography file `my_module_references.bib`.  Here's an example with the textbook for this class [@gelman2013bayesian].  Please see how to add multple `.bib` files to `index.Rmd` [here](https://bookdown.org/yihui/bookdown/citations.html).

## Evaluation Components

- **Clarity.**  Can we understand the content without knowing it already?  Is the material organized into sections and subsections that make it easy to follow?

- **Coding.**  Is the integration of Markdown/LaTeX/Software well organized, easy to follow, and straightforward to maintain/extend?  Also, software should be well commented, and functions and variables should be named in an informative and consistent manner.

	For R naming conventions, I suggest you more or less follow the [tidyverse style guide](https://style.tidyverse.org/).  In particular, you should use `snake_case` for just about everything except classes, which should be in `PascalCase`.  Also, you should never use `dot.case`.

- **Extra Mile.**  Here I'm looking at any indication that you tried to take this content beyond just stringing together the slides and R code posted on LEARN.  This might include: finding good learning and software resources online, relevant papers (including those posted under "reading" on LEARN), adding or finding background material to make things more clear^[Some concepts referred to in the slides may have been introduced in other classes I teach.  If you suspect or hope that this is the case, please contact me as I may be able to send you relevant material.], adding or rewriting code examples using state-of-the-art software.

## Timeline

- **Tuesday May 26:** Send me an email telling me (i) which module you want to work on, (ii) whether you agree to be co-author on the e-book, and (iii) your GitHub username so that I can give you access to the book skeleton and resource materials.

	With this information, students interested in co-authoring the e-book will be notified of who else is working on their module, so that you may coordinate among yourselves who does what.

	Students who do not wish to collaborate on the e-book can make groups as they see fit.

- **Tuesday June 2:** A draft of the module must be uploaded to GitHub (one per group).  The draft must at least contain a detailed outline (sections, subsections, etc. with some text) for the module.

- **Friday June 12:** Final version must be uploaded to GitHub (one per group).  Also, *each student* must submit a PDF file on the LEARN Dropbox summarizing the contribution of each group member to the module.  This can simply contain the line: "all group members contributed equally to this assignment".
